import type { Metadata } from "next";
import { Playfair_Display, Outfit } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Link from "next/link";
import { IconBrandWhatsapp, IconPhone } from "@tabler/icons-react";
import { Button } from "@/components/ui/button";
import { ArrowUp } from "lucide-react";
import { ScrollToTopButton } from "@/components/Button";

const playfair_display = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-display",
  weight: ["400", "700", "900"],
});
const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-body",
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-sans min-h-screen scroll-smooth px-4 antialiased sm:px-8 lg:px-16 ${playfair_display.variable} ${outfit.variable}`}
      >
        <Header />
        <main className="mx-auto flex w-full max-w-7xl flex-col items-center justify-between rounded-2xl border-8 border-stone-200 p-2.5 lg:rounded-[4rem] lg:border-[24px] lg:p-8">
          <div className="flex w-full flex-col rounded-[10px] border-8 border-stone-200 p-3.5 lg:rounded-3xl lg:border-[12px]">
            {children}
          </div>
        </main>
        <Footer />

        <ScrollToTopButton />

        <fieldset className="fixed bottom-0 right-20 space-x-1 text-white">
          <Link
            href={"/"}
            className="inline-flex rounded-t-lg bg-stone-800 p-4"
          >
            <IconPhone />
          </Link>
          <Link
            href={"/"}
            className="inline-flex rounded-t-lg bg-stone-800 p-4"
          >
            <IconBrandWhatsapp />
          </Link>
        </fieldset>
      </body>
    </html>
  );
}
